### ISSUE TITLE
how to video

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/veterans-employment-center#122]
There are some videos that we need to somehow incorporate into careers and employment. They are likely off-brand and also have useful content, so I think we should make some video decisions. 

my 2 cents - we don't bring any "over" and instead link to them in a consistent pattern. 

@gnakm @dannychapman @rcarthur

**Comment by dannychapman** [comment]
@emilyville Agreed re: not bringing videos over. We should discuss this extensively with the content team to make sure any videos meet our content guidelines for voice, tone and content.

**Comment by gnakm** [comment]
@emilyville @dannychapman Me 3! No bringing videos over. I talked to Meg who was working on content for VECI and she mentioned wanting lots of videos on Vets.gov and I kindly explained to her that we will make sure the videos will be reached but our voice and tone is not about the imageries. I digress.

One thing to note is, I saw a usability test where a user was redirected to va.gov and she was completely thrown off by the change of look and feel. It's inevitable since that's going to happen a lot but I think it's good to keep in mind what that redirect-transition experience may be like. Not a good example but yelp has that redirecting pop-up when you click on a restaurant's website. 

<img width="1440" alt="screen shot 2016-02-03 at 5 10 20 pm" src="https://cloud.githubusercontent.com/assets/13420618/12798715/f01eab64-ca98-11e5-8ee6-ae8bb6b5e0a8.png">

**Comment by emilyville** [comment]
Reviving this! 

First off pinging @rcarthur since I think he originally asked the question. Also - @koconnor719 since this came up today.

I think we're agreed on no videos (unless we make them, but this is not in the plan at all.) And only linking off to them. There are two issues - one being that the GI Tool already has a video embedded. I'll see how set we are on keeping that one, and then also see if we need to outline this in our playbook and how much official-ness we need around this decision to make it stick. 

@gnakm I think the idea of softening the landing on the other side (va.gov) is a worthwhile thing to think about. It's tricky since you're not leaving a business or entity - and you'll still be at the VA. Seems like a good thing to address with usability testing and/or research. Especially when we get to sites like the TAPP training one. 

Closing this and I'll take those action items up outside of the githubs. Thanks everyone!
