### ISSUE TITLE
User research on VEC profile deletion

### ISSUE THREAD

**Issue by cfeeney-va** [department-of-veterans-affairs/veterans-employment-center#216]
Hi Gina,
Let me know if you need any additional info for this ticket!
Follow-up for #165 
Currently, functionality exists in VEC to delete created profiles (resumes) but seems non-intuitive.  We'd like to do some follow-up with users to see how it could be improved.
*Note: user must have a DS Login to see this workflow

1. Create profile on the "Build a Profile & Résumé" page 
2. Click "Preview Your Veteran Profile and Résumé Content"->takes you to the profile page. 
3. Click the "Sign in to publicly post your profile" button->takes you through the DS Logon workflow 
4. Complete DS Logon
5. You will be re-routed to the "Edit Profile" page. 
6. Return to the profile page (via the "Preview Your Veteran Profile and Résumé Content" button) 
7.  There will now be a "Delete" button that can be used to delete the profile.

**Comment by gnakm** [comment]
I uploaded the screenshots for reference. 

![2016-02-01_22-35-59](https://cloud.githubusercontent.com/assets/13420618/13672894/b4105fd2-e6a4-11e5-8927-01e957d5551d.png)

I don't think a usability test would be necessary for this unless the issue comes up. My instinct tells me that the workflow and change in look and feel (DS Logon vs. vets.gov) may make the process feel a little daunting but I think the delete button is located in the right place. The "profile page" seems like the proper "settings" page where one can usually find the option to delete or edit an item. 

My only improvement advice is to have the edit profile and delete buttons side by side instead of staking on top of each other.

**Comment by ayaleloehr** [comment]
There are no more profiles, so no research necessary.
