### ISSUE TITLE
coursera and linkedin 

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/veterans-employment-center#292]
are these Veteran benefits highlighted anywhere else on the site? shouldn't these be more prominent since they are free resources for Veterans? they seem hard to find on this page. @mariana-almeida 

![screen shot 2016-04-12 at 11 42 43 pm](https://cloud.githubusercontent.com/assets/13770771/14482213/6b3b8006-0108-11e6-8e0a-5e981ada0fd9.png)

**Comment by mariana-almeida** [comment]
These are all elsewhere on the site more prominently,  in Education area. The only one we link off to on another site is this one: Consider military tuition assistance (for active duty). 

@bethpotts can you please see if we are linking to this on Education side?(http://myarmybenefits.us.army.mil/Home/Benefit_Library/Federal_Benefits_Page/Tuition_Assistance_(TA).html?serv=149)

**Comment by mollyblake** [comment]
@koconnor719 @mariana-almeida I'll field this one! :) We link to LinkedIn elsewhere including from the job search page where there is a piano key. 

As far as Coursera is concerned, we have a piano key off the job search page.  But I will re-tool the text on this page that contains the Coursera class and that will make it a bit more prominent. 

And yes, @mariana-almeida we are linking to that MyArmy Benefits site because the TA program is branch specific. We debated about listing out each branch and linking to each but this seemed like a good option.

**Comment by koconnor719** [comment]
thanks.  it just seems like these 2 free resources are buried at the bottom of the job seeker page in tiny font:)

**Comment by koconnor719** [comment]
@mariana-almeida that's good they are in other places on the site:)  but given these are free employment resources that VA has partnered w/ for Veterans--shouldn't they be highlighted more on the job seeker page?  the Interest profiler (which we heard from feedback is not helpful) is more prominent on the subway map than these 2 free benefits?

**Comment by mollyblake** [comment]
Hi @koconnor719 I've been working on this issue and am happy to work on making these resources more prominent !  Thanks

**Comment by koconnor719** [comment]
i think this is  a design question?  @emilyville pls advise:)

**Comment by gnakm** [comment]
I'm closing this out because it's being worked on #2121

**Comment by koconnor719** [comment]
Ty!
Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436
