### ISSUE TITLE
Viewing output of skills translator

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#69]
<a href="https://github.com/cfeeney-va"><img src="https://avatars.githubusercontent.com/u/15927676?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cfeeney-va](https://github.com/cfeeney-va)**
_Wednesday Dec 09, 2015 at 18:35 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/383_

----

Since the skills translator shows the results on the same page below the input boxes, it can be difficult to see.  Using a standard-ish size window, the information populated below the page break for me, so I didn't realize the website had responded and at first thought it was broken.  Could we have the page auto-scroll down to display the results when the user hits "translate"?

**Comment by ayaleloehr** [comment]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MarinaMartin](https://github.com/MarinaMartin)**
_Monday Dec 21, 2015 at 05:54 GMT_

----

As a stop-gap, I added the text "Scroll down for results" below the translate button. Someone with UX skills likely has a better idea.

**Comment by gnakm** [comment]
@MarinaMartin Unfortunately, I think the "scroll" text gets totally missed. And @cfeeney-va  I don't think an auto-scroll is the best solution because I think it won't be user-friendly for our not tech-savvy or older users. What needs to happen is for the the results to be right underneath the search box. Here is a quick solution however I think we need to talk about to copy. It's not that informative in my opinion and sort of messes up the sequencing of the search, results, and buttons. 
**
What it currently looks like after "translating"**
![current window](https://cloud.githubusercontent.com/assets/13420618/12834076/dd00e4a4-cb72-11e5-8de7-36036d2c269c.png)
__


**New Mockup**
![current page skills](https://cloud.githubusercontent.com/assets/13420618/12834092/f26baa2c-cb72-11e5-8c23-aa17593eef41.png)
__

**
New Mockup before "translating"**
![new skill page](https://cloud.githubusercontent.com/assets/13420618/12834107/0e05157a-cb73-11e5-883f-26f83486c0e5.png)
__


**New Mockup after "translating"**
![skill page results](https://cloud.githubusercontent.com/assets/13420618/12834101/fc8b7c9e-cb72-11e5-8259-3a852f0fb630.png)
__

**Comment by emilyville** [comment]
This looks awesome! Once this is out we can tag the content people for some
new copy - I don't think it's in the ia they sent yesterday.

**Comment by ayaleloehr** [comment]
This is OBE by the new Skills Translator design. Closing.
