### ISSUE TITLE
"Available as of" should be on 1 line, not 3

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/veterans-employment-center#83]
<a href="https://github.com/MarinaMartin"><img src="https://avatars.githubusercontent.com/u/489465?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 05:17 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/459_

----

In Veteran search:

![image](https://cloud.githubusercontent.com/assets/489465/11948367/4ef9ae24-a841-11e5-8338-f20a9b708bca.png)

**Comment by akainic** [comment]
@emilyville @ayaleloehr The reason why there are 3 lines is because this is a date select (a line each for month, day, and year). It looks funny because of the way it's styled. I could simply change the styling to look something like this: 
<img width="987" alt="screenshot 2016-02-02 11 14 13" src="https://cloud.githubusercontent.com/assets/3886085/12757756/58f76506-c9a7-11e5-8fa0-24740da92c64.png">

One problem I've encountered with doing this is that I would need to wrap each select in a Foundation class (`small-4 columns`). However, these selects are automatically generated all together with a Rails form helper. There isn't a straightforward way of wrapping each individually with a div (as far as I can tell). It looks like [Simple Form](https://github.com/plataformatec/simple_form) has a solution for this, but I'm not sure if we want to add a whole new gem for this problem. I could do something hacky with the CSS to fake the right styling, but that doesn't seem like a very extensible solution.

The other option is to use a jQuery UI datepicker, which should be supported all the way back to IE8, but that's an entirely new UI choice.

Thoughts?

**Comment by emilyville** [comment]
@akainic I know this problem well - we have encountered it with simple form, too! The simple form solution - if I'm remembering correctly - is to strip all styles, leaving you with the same problem of generating a bunch more custom CSS. 

It's a long shot, but since we do have some other columns built in, do you think moving the date to the last line might give us more options for columns w/o adding a bunch of work ? I don't think it needs to go in the specific order it is in. Also take a look at resume builder, not sure how we had more customization there, but building this form the same way wouldn't be a bad direction. 

#notthathelpful

**Comment by akainic** [comment]
@emilyville Thanks for looking at this! I was reading the docs on [simple form](https://github.com/plataformatec/simple_form) and it looks like they have an attribute you can pass to the input that wraps the input and label in a wrapper div, `wrapper_html`, which you can then specify the class for. I haven't actually tried using it, but it looked like it might solve this problem! 

I tried moving the date select to the last question in the form, and it's still the same problem. The only way to add columns to the individual date dropdowns is to add them to the selects themselves, and because of that the selects absorb the padding that the wrapper div ordinarily should have, so they appear slightly longer. 
<img width="1082" alt="screenshot 2016-02-03 09 03 20" src="https://cloud.githubusercontent.com/assets/3886085/12784428/2e553fea-ca55-11e5-8e6a-3c56282d1681.png">

I'll play around with this a bit more and see if there's anything else I can come up with, other than applying unique CSS styles on date selects without relying on Foundation for these situations.

**Comment by ayaleloehr** [comment]
There will be no more Veteran search after removing the profile bank, so this seems no longer relevant.
